export const tiposFuente = [
   "Arial",
   "Arial Black",
   "Book Antiqua",
   "Calibri",
   "Charcoal",
   "Comic Sans MS",
   "Courier",
   "Courier New",
   "cursive",
   "Gadget",
   "Geneva",
   "Georgia",
   "Helvetica",
   "Impact",
   "Lucida Console",
   "Lucida Grande",
   "Lucida Sans Unicode",
   "Monaco",
   "monospace",
   "Palatino",
   "sans-serif",
   "serif",
   "Tahoma",
   "Times New Roman",
   "Times",
   "Trebuchet MS",
   "Verdana",
];
